"""Экспортирует справочные данные NTP в shared/ntp-data.json.

Этот файл читает Android-модуль: он генерирует из него Kotlin на этапе сборки.
Источник правды — константы в src/android_time_fixer.py, а JSON выводится
отсюда, чтобы обе половины проекта не разъехались. Расхождение ловит тест
test_shared_ntp_data_matches_the_source, поэтому после правки таблиц скрипт
нужно перезапустить.

Использование:
    python scripts/export_ntp_data.py           # записать файл
    python scripts/export_ntp_data.py --check   # только проверить актуальность
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'src'))
from android_time_fixer import (  # noqa: E402
    COUNTRY_NAMES,
    CUSTOM_NTP_SERVERS,
    NTP_SERVERS,
)

TARGET = Path(__file__).resolve().parent.parent / 'shared' / 'ntp-data.json'


def build_payload() -> dict:
    """Собирает данные в форму, одинаково удобную Python и Kotlin.

    Страны кладём списком объектов, а не словарём: так у записи есть
    естественный порядок, и Kotlin-генератору не нужно гадать про сортировку.
    """
    countries = []
    for code in sorted(NTP_SERVERS):
        english, russian = COUNTRY_NAMES[code]
        countries.append({
            'code': code,
            'server': NTP_SERVERS[code],
            'name_en': english,
            'name_ru': russian,
        })
    return {
        '_comment': (
            'Generated by scripts/export_ntp_data.py from '
            'src/android_time_fixer.py. Do not edit by hand.'
        ),
        'countries': countries,
        'alternative_servers': list(CUSTOM_NTP_SERVERS),
    }


def serialise(payload: dict) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False) + '\n'


def main() -> int:
    payload = serialise(build_payload())

    if '--check' in sys.argv:
        if not TARGET.exists():
            print(f"{TARGET} отсутствует — запустите скрипт без --check")
            return 1
        if TARGET.read_text(encoding='utf-8') != payload:
            print(f"{TARGET} устарел — перезапустите scripts/export_ntp_data.py")
            return 1
        print(f"{TARGET} актуален")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(payload, encoding='utf-8')
    data = json.loads(payload)
    print(f"записано: {len(data['countries'])} стран, "
          f"{len(data['alternative_servers'])} альтернативных серверов -> {TARGET}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
