package com.civisrom.tvtimefixer.terminal

import com.civisrom.tvtimefixer.R

// Desktop examples and AOSP adb.1, with availability specific to this Android client.
internal val additionalTerminalExamples: Map<String, List<CommandExample>> = mapOf(
    "connection" to listOf(
        CommandExample("reference_1", R.string.terminal_reference_1, "adb devices -l", true),
        CommandExample("reference_5", R.string.terminal_reference_5, "adb disconnect IP:PORT", true),
        CommandExample("reference_15", R.string.terminal_reference_15, "adb --help", true),
        CommandExample("reference_16", R.string.terminal_reference_16, "adb help", true),
    ),
    "files" to listOf(
        CommandExample("reference_24", R.string.terminal_reference_24, "adb push \"local file.txt\" /sdcard/Download/file.txt", true),
        CommandExample("reference_25", R.string.terminal_reference_25, "adb pull /sdcard/Download/file.txt \"local file.txt\"", true),
        CommandExample("reference_28", R.string.terminal_reference_28, "adb shell ls -l /sdcard/Download", true),
        CommandExample("reference_30", R.string.terminal_reference_30, "adb shell mv /sdcard/Download/old.txt /sdcard/Download/new.txt", true),
        CommandExample("reference_31", R.string.terminal_reference_31, "adb shell rm /sdcard/Download/file.txt", true),
        CommandExample("reference_32", R.string.terminal_reference_32, "adb shell rmdir /sdcard/Download/adb-demo", true),
        CommandExample("reference_33", R.string.terminal_reference_33, "adb shell screencap -p /sdcard/screen.png", true),
        CommandExample("reference_34", R.string.terminal_reference_34, "adb pull /sdcard/screen.png screen.png", true),
        CommandExample("reference_35", R.string.terminal_reference_35, "adb shell screenrecord --time-limit 30 /sdcard/demo.mp4", true),
        CommandExample("reference_36", R.string.terminal_reference_36, "adb pull /sdcard/demo.mp4 demo.mp4", true),
    ),
    "apps" to listOf(
        CommandExample("reference_37", R.string.terminal_reference_37, "adb install \"app.apk\"", true),
        CommandExample("reference_38", R.string.terminal_reference_38, "adb install -r \"app.apk\"", true),
        CommandExample("reference_39", R.string.terminal_reference_39, "adb install-multiple \"base.apk\" \"split_config.apk\"", true),
        CommandExample("reference_42", R.string.terminal_reference_42, "adb shell pm list packages", true),
        CommandExample("reference_45", R.string.terminal_reference_45, "adb shell pm uninstall --user USER_ID PACKAGE", true),
        CommandExample("reference_46", R.string.terminal_reference_46, "adb shell pm disable-user --user USER_ID PACKAGE", true),
        CommandExample("reference_47", R.string.terminal_reference_47, "adb shell pm enable --user USER_ID PACKAGE", true),
        CommandExample("reference_48", R.string.terminal_reference_48, "adb shell pm clear --user USER_ID PACKAGE", true),
        CommandExample("reference_49", R.string.terminal_reference_49, "adb shell am start -n PACKAGE/ACTIVITY", true),
        CommandExample("reference_52", R.string.terminal_reference_52, "adb shell am broadcast -a ACTION", true),
        CommandExample("reference_extra_2", R.string.terminal_reference_extra_2, "adb uninstall -k PACKAGE", true),
    ),
    "input" to listOf(
        CommandExample("reference_57", R.string.terminal_reference_57, "adb shell input tap X Y", true),
        CommandExample("reference_58", R.string.terminal_reference_58, "adb shell input swipe X1 Y1 X2 Y2 DURATION_MS", true),
    ),
    "time" to listOf(
        CommandExample("reference_66", R.string.terminal_reference_66, "adb shell settings delete global ntp_server", true),
    ),
    "logs" to listOf(
        CommandExample("reference_73", R.string.terminal_reference_73, "adb shell dumpsys SERVICE", true),
        CommandExample("reference_75", R.string.terminal_reference_75, "adb logcat -b crash -d", true),
        CommandExample("reference_76", R.string.terminal_reference_76, "adb logcat", true),
        CommandExample("reference_extra_1", R.string.terminal_reference_extra_1, "adb bugreport", true),
    ),
    "services" to listOf(
        CommandExample("reference_100", R.string.terminal_reference_100, "adb reboot bootloader", true),
        CommandExample("reference_102", R.string.terminal_reference_102, "adb reboot sideload", true),
        CommandExample("reference_103", R.string.terminal_reference_103, "adb reboot sideload-auto-reboot", true),
        CommandExample("reference_108", R.string.terminal_reference_108, "adb disable-verity", true),
        CommandExample("reference_109", R.string.terminal_reference_109, "adb enable-verity", true),
        CommandExample("reference_extra_0", R.string.terminal_reference_extra_0, "adb remount", true),
    ),
)

internal val additionalTerminalCategories: List<CommandCategory> = listOf(
    CommandCategory("help_device", R.string.terminal_category_help_device, listOf(
        CommandExample("reference_115", R.string.terminal_reference_115, "adb exec-out COMMAND", true),
        CommandExample("reference_118", R.string.terminal_reference_118, "adb shell toybox", true),
        CommandExample("reference_122", R.string.terminal_reference_122, "adb shell cmd SERVICE help", true),
        CommandExample("reference_124", R.string.terminal_reference_124, "adb shell input --help", true),
        CommandExample("reference_125", R.string.terminal_reference_125, "adb shell dumpsys --help", true),
        CommandExample("reference_126", R.string.terminal_reference_126, "adb shell top --help", true),
        CommandExample("reference_127", R.string.terminal_reference_127, "adb shell screenrecord --help", true),
        CommandExample("reference_128", R.string.terminal_reference_128, "adb logcat --help", true),
        CommandExample("reference_extra_5", R.string.terminal_reference_extra_5, "adb shell cmd package help", true),
    )),
    CommandCategory("pc_options", R.string.terminal_category_pc_options, listOf(
        CommandExample("reference_18", R.string.terminal_reference_18, "adb [-d | -e | -s SERIAL | -t ID] COMMAND", false),
        CommandExample("reference_19", R.string.terminal_reference_19, "adb -H HOST -P PORT COMMAND", false),
        CommandExample("reference_20", R.string.terminal_reference_20, "adb -L SOCKET start-server", false),
        CommandExample("reference_21", R.string.terminal_reference_21, "adb -a start-server", false),
        CommandExample("reference_22", R.string.terminal_reference_22, "adb --one-device SERIAL start-server", false),
        CommandExample("reference_23", R.string.terminal_reference_23, "adb --exit-on-write-error COMMAND", false),
    )),
    CommandCategory("pc_ports", R.string.terminal_category_pc_ports, listOf(
        CommandExample("reference_82", R.string.terminal_reference_82, "adb forward --list", false),
        CommandExample("reference_83", R.string.terminal_reference_83, "adb forward [--no-rebind] tcp:6100 tcp:7100", false),
        CommandExample("reference_84", R.string.terminal_reference_84, "adb forward --remove tcp:6100", false),
        CommandExample("reference_85", R.string.terminal_reference_85, "adb forward --remove-all", false),
        CommandExample("reference_86", R.string.terminal_reference_86, "adb reverse --list", false),
        CommandExample("reference_87", R.string.terminal_reference_87, "adb reverse [--no-rebind] tcp:7100 tcp:6100", false),
        CommandExample("reference_88", R.string.terminal_reference_88, "adb reverse --remove tcp:7100", false),
        CommandExample("reference_89", R.string.terminal_reference_89, "adb reverse --remove-all", false),
    )),
    CommandCategory("pc_tools", R.string.terminal_category_pc_tools, listOf(
        CommandExample("reference_3", R.string.terminal_reference_3, "adb -s SERIAL shell getprop ro.product.model", false),
        CommandExample("reference_4", R.string.terminal_reference_4, "adb -d shell getprop ro.product.model", false),
        CommandExample("reference_9", R.string.terminal_reference_9, "adb get-devpath", false),
        CommandExample("reference_10", R.string.terminal_reference_10, "adb mdns check", false),
        CommandExample("reference_11", R.string.terminal_reference_11, "adb mdns services", false),
        CommandExample("reference_12", R.string.terminal_reference_12, "adb pair IP:PAIR_PORT [CODE]", false),
        CommandExample("reference_13", R.string.terminal_reference_13, "adb -d tcpip 5555", false),
        CommandExample("reference_14", R.string.terminal_reference_14, "adb -s SERIAL usb", false),
        CommandExample("reference_17", R.string.terminal_reference_17, "adb version", false),
        CommandExample("reference_26", R.string.terminal_reference_26, "adb push [--sync] [-z ALGORITHM | -Z] [-n] [-q] LOCAL... REMOTE", false),
        CommandExample("reference_27", R.string.terminal_reference_27, "adb pull [-a] [-z ALGORITHM | -Z] [-q] REMOTE... LOCAL", false),
        CommandExample("reference_40", R.string.terminal_reference_40, "adb install-multi-package \"first.apk\" \"second.apk\"", false),
        CommandExample("reference_41", R.string.terminal_reference_41, "adb uninstall [-k] PACKAGE", false),
        CommandExample("reference_77", R.string.terminal_reference_77, "adb bugreport bugreport.zip", false),
        CommandExample("reference_78", R.string.terminal_reference_78, "adb jdwp", false),
        CommandExample("reference_79", R.string.terminal_reference_79, "adb host-features", false),
        CommandExample("reference_80", R.string.terminal_reference_80, "adb features", false),
        CommandExample("reference_81", R.string.terminal_reference_81, "adb server-status", false),
        CommandExample("reference_90", R.string.terminal_reference_90, "adb start-server", false),
        CommandExample("reference_91", R.string.terminal_reference_91, "adb kill-server", false),
        CommandExample("reference_92", R.string.terminal_reference_92, "adb reconnect", false),
        CommandExample("reference_93", R.string.terminal_reference_93, "adb reconnect device", false),
        CommandExample("reference_94", R.string.terminal_reference_94, "adb reconnect offline", false),
        CommandExample("reference_95", R.string.terminal_reference_95, "adb wait-for-device", false),
        CommandExample("reference_96", R.string.terminal_reference_96, "adb wait-for-TRANSPORT-STATE", false),
        CommandExample("reference_97", R.string.terminal_reference_97, "adb -s SERIAL attach", false),
        CommandExample("reference_98", R.string.terminal_reference_98, "adb -s SERIAL detach", false),
        CommandExample("reference_104", R.string.terminal_reference_104, "adb sideload \"update.zip\"", false),
        CommandExample("reference_107", R.string.terminal_reference_107, "adb remount [-R]", false),
        CommandExample("reference_110", R.string.terminal_reference_110, "adb keygen \"new-adb-key\"", false),
        CommandExample("reference_111", R.string.terminal_reference_111, "adb sync [-l] [-n] [-q] [-z ALGORITHM | -Z] [PARTITION]", false),
        CommandExample("reference_112", R.string.terminal_reference_112, "adb emu help", false),
        CommandExample("reference_113", R.string.terminal_reference_113, "adb emu COMMAND", false),
        CommandExample("reference_114", R.string.terminal_reference_114, "adb shell [-e ESCAPE] [-n] [-T | -t | -tt] [-x] [COMMAND...]", false),
        CommandExample("reference_116", R.string.terminal_reference_116, "adb exec-in COMMAND", false),
        CommandExample("reference_extra_3", R.string.terminal_reference_extra_3, "adb attach", false),
        CommandExample("reference_extra_4", R.string.terminal_reference_extra_4, "adb detach", false),
    )),
)
