name: Update dependencies

on:
  schedule:
    - cron: "0 0 1 * *"  # Пример расписания для обновления зависимостей раз в месяц
  workflow_dispatch:  # Также можно запускать вручную

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update dependencies with Poetry
        run: |
          poetry update

      - name: Commit updated dependencies
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add poetry.lock
          git commit -m "Update dependencies"
          
      - name: Create pull request with updated dependencies
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-dependencies-${{ github.sha }}
          title: Update dependencies
          body: This PR updates dependencies to their latest versions.
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[create-pull-request] automated change"
          committer: GitHub <noreply@github.com>
          author: civisrom <civisrom@users.noreply.github.com>
          base: main  # Целевая ветка для PR
          signoff: false
          delete-branch: false
          draft: false
