name: Update dependencies

on:
  schedule:
    - cron: "0 0 1 * *"  # Обновление зависимостей раз в месяц
  workflow_dispatch:  # Возможность запуска вручную

env:
  PYTHON_VERSION: '3.10'
  CI_DEBUG: true
  POETRY_VERSION: '1.8.4'
  PYINSTALLER_VERSION: '6.11.1'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
        
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ env.POETRY_VERSION }}
        shell: bash
        
      - name: Configure Poetry Environment
        run: |
          # Determine Python executable
          PYTHON_EXE=$(which python)
            
          # Verify Python version
          $PYTHON_EXE --version
            
          # Set up Poetry environment with specific Python version
          $PYTHON_EXE -m poetry env use $PYTHON_EXE
            
          # Configure Poetry settings
          $PYTHON_EXE -m poetry config virtualenvs.create true
          $PYTHON_EXE -m poetry config virtualenvs.in-project true
            
          # Verify Poetry environment
          $PYTHON_EXE -m poetry env info
        shell: bash
        
      - name: Install Project Dependencies
        run: |
          python -m poetry config virtualenvs.in-project true
          python -m poetry lock
          python -m poetry install --no-interaction --no-root
          python -m poetry install --no-interaction --with dev --all-extras
          python -m poetry run pip install pyinstaller==${{ env.PYINSTALLER_VERSION }}
        shell: bash
          
          
      - name: Configure Poetry Environment (Windows)
        run: |
          # Windows-specific Poetry environment setup
          python -m poetry env use "$env:pythonLocation\python.exe"
          python -m poetry config virtualenvs.create true
          python -m poetry config virtualenvs.in-project true
          python -m poetry env info
        shell: pwsh
        
      - name: Verify Python version
        run: python --version

      # Шаг 2.1: Очищаем кэш Poetry
      - name: Clear Poetry cache
        run: |
          rm -rf ~/.cache/pypoetry

      # Шаг 3: Кэшируем зависимости Poetry
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      # Шаг 5: Принудительное обновление зависимостей
      - name: Update dependencies
        run: |
          poetry self update
          poetry lock
          poetry install
          poetry update
        env:
          POETRY_CACHE_DIR: ~/.cache/pypoetry  # Используем кэш Poetry

      # Шаг 6: Настраиваем пользователя Git
      - name: Configure Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      # Шаг 7: Проверяем изменения и пушим их
      - name: Commit and push changes to main
        run: |
          git add poetry.lock
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update dependencies"
            git push origin main
          fi
